Feat/core generator onehot
algebra-club/TaguPy pull request #12
Opened 2021-08-22 13:09 UTC by yo-aka-gene

* TaguPy version:
* Python version:
* Operating System:

### What

add Onew Hot Design

### Why

rehersal for PB implementation

2021-08-22 13:12 UTC, takesei commented
- 可能であればタイトルをもう少しわかりやすいものにしていただけますか
- One hot designとはなんなのかの説明も手いただけますか

2021-08-22 13:17 UTC, takesei commented
<img width="673" alt="Screen Shot 2021-08-22 at 22 16 46" src="https://user-images.githubusercontent.com/10820903/130356679-d6399e20-9aea-422e-baed-efa78fc7d7ce.png">
これそもそもテスト実行されていなさげですね...

2021-08-22 14:38 UTC, takesei requested changes

2021-08-22 14:38 UTC, takesei commented on tagupy/core/generator/onehot.py
> +            )
これlinebreakしすぎててみにくいかもしれませんね... identの位置とかまずは揃えてみましょうか

2021-08-22 14:38 UTC, takesei commented on tagupy/core/generator/onehot.py
> +    def get_alias_matrix(self, max_dim: int = 1) -> np.ndarray:
2時以降の交互作用が見れないのであればそもそも引数として要求する必要はありますか?

2021-08-22 14:38 UTC, takesei commented on tagupy/core/generator/onehot.py
> +        therefore max_dim expected to be 1
max_dimの下りは上記の理由より要らないのでは?

2021-08-22 14:38 UTC, takesei commented on tagupy/core/generator/onehot.py
> +            f"Error: value of max_dim should be lower than n_factor"
ここのテストも同様に

基本的にエラーが起きた理由を示してあげた方がいいので, fstring使用した方がいいとは思います.

```python
assert max_dim <= self.n_factor, \
            f"Error: value of max_dim should be lower than n_factor, expect max_dim <= {n_factor}, got {max_dim}"
```

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +"""
全体的にtest caseが足りない気がします...もう少し増やしてもいいかもしれません. 一回だけだと適当なものでも通る可能性がありますが, nを稼ぐことでうっかり通ってしまった...という実装を減らせるものなので

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +from tagupy.core.generator.onehot import OneHot
呼び出し方はこれが理想ですか?

個人的には
```python
from tagupy.core.generator import OneHot
```

となるように組んであげるのがいいと思います.
もしかしたらcoreもいらないかもね

2021-08-22 14:38 UTC, takesei commented on tagupy/core/generator/onehot.py
> +            f"Error: n_rep expected integer >= 1"
input valueを教えてあげてください

2021-08-22 14:38 UTC, takesei commented on tagupy/core/generator/onehot.py
> +            f"Error: n_rep expected int, got {type(self.n_rep)}"
pythonは型のない言語なので, こういう記述はあまりしないのですが...
もししたい場合は別の言語を使うか下のようなものを使います
https://github.com/samuelcolvin/pydantic

2021-08-22 14:38 UTC, takesei commented on tagupy/core/generator/onehot.py
> +            f"Error: n_rep expected int, got {type(self.n_rep)}"
型のないというのは語弊がありました, 動的なtypingという話です

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        OneHot(arg)
（上でassertionいらないのではと入ったので一般のtestのことだと思って聞いて欲しいのですが）
せっかくdtypeについてのdynamicなerror messageを書いたのであればそちらを試してみては?

```python
with pytest.raises(AssertionError) as e:
    OneHot(arg)
assert f'{type(arg)}' in e.value, \
    f'Error message must contain the reason > expect {type(arg)} in the msg, got {e.value}'
```

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        OneHot(arg)
あとよく考えたらもし↑のテストを書くのであれば出すべきエラーはAssertionではなくて, TypeErrorですね

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        OneHot(**kwargs)
ここのテストの気持ちを教えてもらってもいいですか?

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        "Error: default value for n_rep is not 1"
この書き方でもいいのですが, OneHot()でエラーが出てしまった場合にassertと空見するかもしれないので分けた方がベターです

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +
そもそも実行ができるか...というタイプのtestがない気がします

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +    assert type(OneHot(n_rep).get_exmatrix(arg)) == np.ndarray, \
複雑度高いので分けてきた方がいいですねここは

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        OneHot(n_rep).get_exmatrix(arg)
これ言語機能的に落ちませんか & TypeErrorでは?

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +    _model = OneHot(n_rep).get_exmatrix(n_factor)
n_rep = 1と明示的に示した方がいいですねここは...

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        "Error: exmatrix should be identity matrix when n_rep == 1"
本質的に順番は大事なのでしょうか? sortしたら一致しているとかならわかるのですが, identityでないといけない?

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        "Error: exmatrix should be identity matrix when n_rep == 1"
また, shapeのテストと一緒にしちゃってもいいのでは?

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        "Error: something is wrong with replication"
それぞれn_rep回ずつ出てきている, それぞれの実験で出てきているonなものは1回

といったところでテストを書いたらn_repに対して一般化できませんか?

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +
関数に設定している以上の引数が入る / 以下の引数が入った場合は言語使用的にerrorが出ると思うのですが, その言語使用てきな部分まで我々は責任を負う必要があると思いますか

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +    arg = 0
infoなどの引数の名前に合わせるのか, argで統一するのかした方がいいです

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +    assert type(_model.get_alias_matrix(dim)) == np.ndarray, \
typeではなくisinstanceを使ってください

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +    assert type(OneHot(n_rep).get_exmatrix(arg)) == np.ndarray, \
typeではなくisinstanceを使ってください

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        "Error: something is wrong with alias_matrix"
output出したって

2021-08-22 14:38 UTC, takesei commented on tests/core/generator/test_onehot.py
> +        "Error: something is wrong with alias_matrix"
https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_equal.html

後これ使ってもいいのよ

2021-08-22 19:06 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +    def __init__(self, n_rep: int = 1):
n = 3なら明示的にインプットする気になるけど、繰り返さないときにn = 1って入力しないといけないのアホくさいかなって思ってデフォルトでn = 1にしたんですが、どうでしょうか（繰り返さないっていう場合が果たしてどれくらいあるのかっていう問題はありますが）

2021-08-22 19:12 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +
いや、まったくないですね
Pythonの仕様で落ちることを知っていながら、まあ一応書いておいた方が無難なのかなくらいの気持ちで書きました

2021-08-22 19:28 UTC, yo-aka-gene commented on tagupy/core/__init__.py
> +__version__ = '0.1.0'
core/generatorの中に同じような__init__.pyで指定してあげることになるのでしょうか？

2021-08-22 19:31 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +    def get_alias_matrix(self, max_dim: int = 1) -> np.ndarray:
_Generatorでの定義に合わせた方がいいのかなと思ったのですが、引数をselfだけにした方がいいってことでしょうか

2021-08-22 19:33 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +from tagupy.core.generator.onehot import OneHot
その方がいいと思います

2021-08-22 19:37 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +        OneHot(n_rep).get_exmatrix(arg)
make testとmake test-allでは一応onehot.pyは全部通ってたのですが
make coverage, make lintも確認してからpushしました

2021-08-22 19:50 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        self.n_factor = n_factor
PBなどの他の方法では、exmatrixを保存しておいた方がailias_matrixが書きやすいと思ったので、それに合わせたのですがいかがでしょうか
one hotだけに限れば、ailias_matrixの生成方法に関与していないのでいらないと思います

2021-08-22 20:11 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +            f"Error: n_rep expected int, got {type(self.n_rep)}"
全くわからないのですが、_GeneratorではなくBasalModelで定義する必要があるということでしょうか？

2021-08-22 20:14 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        self.exmatrix = _res
上記と同様、PBなどの方法では保持していた方が後々都合がいいかと思って、それに合わせた方がいいのかなと思いましたが、いかがでしょうか
（未だにライブラリ全体としての一貫性を重視するべきなのか、moduleごとの最小限の機能を目指すべきなのかがわかってません、申し訳ございません）

2021-08-22 20:15 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        therefore max_dim expected to be 1
上記と同様です

2021-08-22 20:26 UTC, yo-aka-gene commented on tagupy/core/__init__.py
> +__version__ = '0.1.0'
解決しました、お騒がせいたしました

2021-08-22 20:44 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +from tagupy.core.generator.onehot import OneHot
coreをすっ飛ばしてインポートできるようにする方法がイマイチよくわからないので（シンボリックリンクでもtagupy直下に入れておくのでしょうか？）、指摘してもらった感じに直しておきます

2021-08-22 20:46 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +        OneHot(**kwargs)
謎の変数を入れられたら、エラーが出て欲しいっていうことなんですが、Pythonの機能で勝手に落ちてくれるんだけどなあとも思いながら、一応テストに書いた方がいいのか悩んだ結果なので、消しておきます

2021-08-22 21:27 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +    _model = OneHot(n_rep).get_exmatrix(n_factor)
ごめんなさい、ご指摘の内容がわかりませんでした

2021-08-22 21:36 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +            f"Error: n_rep expected int, got {type(self.n_rep)}"
ひとまず、n_repがintじゃない場合は、キャストしておく仕様に変えておきます

2021-08-22 21:37 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +    def __init__(self, n_rep: int = 1):
下に書きましたが、n_repがintじゃない場合はキャストしておく仕様に変えておきますので、やっぱりデフォルトバリューなしにしますw

2021-08-22 21:53 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        self.n_factor = n_factor
やっぱり誤解を招きそうなので、仕様に無関係なものは消しておきます

2021-08-22 21:58 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        self.exmatrix = _res
やっぱり、混乱を招かないように、不要なインスタンスを持たないようにします
（一方で、n_factorはエイリアスマトリックスで再利用したいので、一応残しておきます）

2021-08-22 22:00 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +    def get_alias_matrix(self, max_dim: int = 1) -> np.ndarray:
まあ使わないので消しておきます

2021-08-22 22:47 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +    _model = OneHot(n_rep).get_exmatrix(n_factor)
n_rep == const. or f_factor == const.で場合分けしておきました

2021-08-22 23:19 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +        "Error: exmatrix should be identity matrix when n_rep == 1"
下のやつとまとめて書き直します

2021-08-22 23:21 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +    arg = 0
引数を取らないように変更したので、削除しました

2021-08-23 00:12 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        return np.ones((self.n_factor, self.n_factor))
よく考えたら、ここの実装間違ってた
でも、pandas.DataFrame(np.corrcoef(self.exmatrix))とpandas.DataFrame(self.exmatrix).corr()の結果が一致してなくて、実装に迷ってます。
ここについて相談しましょう

2021-08-23 00:14 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +    exp = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
上でも書きましたが、よく考えたら間違ってたんですが、正解もよくわからないので、相談したいです

2021-08-23 00:14 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +        "Error: something is wrong with alias_matrix"
保留にしておきました

2021-08-23 00:15 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        return np.ones((self.n_factor, self.n_factor))
とりあえず保留にしておきました

2021-08-23 00:24 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        return self.exmatrix
変更しだすと色々めんどいけど、この実装だと、ネガコンって考えられないんですよね...

2021-08-23 00:27 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +    _Generator Class of One Hot Design Generator Module
正直、僕もOne Hotの定義よく知らない
ネガコンいるいらないで実装結構変わりそう
でも全部０の行あると、One Hotじゃなくなるんだよなあ
悩む

2021-08-23 00:57 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +        return self.exmatrix \
ここの実装は明らかに間違っているのですが、そもそもエイリアスマトリックスの正解が謎なので保留にしたいです（マージしなくてOK）
pandas.DataFrame(self.exmatrix).corr()とpandas.DataFrame(np.corrcoef(self.exmatrix))が不一致なのでわからないので、相談したいです

2021-08-23 01:00 UTC, yo-aka-gene commented on tests/core/generator/test_onehot.py
> +# alias matrixの実装について相談したいので、一旦保留にします
これも上記と同じくほりゅう

2021-08-23 01:16 UTC, yo-aka-gene commented on tagupy/core/generator/onehot.py
> +
One Hot Designの定義が謎
One Hot Vectorが行としても列としても並んでいるっていう認識（一応’こっちを採用しています）だと、ネガコンが存在しない感じになってしまう（ネガコンが必要ならテストも実装の修正が必要）

2021-08-23 13:36 UTC, taka-sho commented on .python-version
> +3.9.6
ignore した方がいいね

2021-08-23 14:34 UTC, taka-sho commented on tests/core/generator/test_onehot.py
> +def test_init_input_dtype():
レッドパターンはネガティブな単語をテスト名に入れたいです

2021-08-28 09:21 UTC, yo-aka-gene commented on tagupy/design/generator/_onehot.py
> +
get_alias_matrixはもう存在しないメソッド

2021-08-28 11:53 UTC, takesei reviewed
LGTM

2021-08-28 11:56 UTC, gk-hazard approved these changes
LGTM

2021-08-28 11:56 UTC, takesei approved these changes

2021-08-28 11:57 UTC, taka-sho approved these changes
![LGTM](https://image.lgtmoon.dev/138633)

2021-08-28 11:59 UTC, merged