:tada: add Plackett-Burman Design Generator Module
algebra-club/TaguPy pull request #27
Opened 2021-09-04 09:03 UTC by yo-aka-gene

* TaguPy version:
* Python version:
* Operating System:

### What

Implement of PB Design Generator Module

### Why

PB design is a part of  representative methods of DOE

2021-09-04 10:49 UTC, taka-sho requested changes

2021-09-04 10:49 UTC, taka-sho commented on tagupy/design/generator/_plackettburman.py
> +        ][i//4] for i in range(100)]
視認性向上のため，演算子の左右はスペースを含めたいです

2021-09-04 10:49 UTC, taka-sho commented on tests/design/generator/test_pb_ref.py
> +            f"dtype of retrun var expected np.ndarray, got {type(matrix)} in _pb{num}"
エラーメッセージに関しては `numpy.ndarray` の表記の方が初心者にも優しいかもです

2021-09-04 10:54 UTC, yo-aka-gene commented on tagupy/design/generator/_plackettburman.py
> +        ][i//4] for i in range(100)]
直しました！

2021-09-04 10:55 UTC, yo-aka-gene commented on tests/design/generator/test_pb_ref.py
> +            f"dtype of retrun var expected np.ndarray, got {type(matrix)} in _pb{num}"
他の箇所も含めて直しておきました

2021-09-04 12:54 UTC, taka-sho approved these changes
![LGTM](https://image.lgtmoon.dev/124253)

2021-09-06 13:45 UTC, takesei requested changes
取り急ぎ

2021-09-06 13:45 UTC, takesei commented on tagupy/design/generator/__init__.py
> +    "_pb_ref",
`_pb_ref`を外部に読み込ませる必要ありますか?

2021-09-06 13:45 UTC, takesei commented on tagupy/design/generator/_plackettburman.py
> +    get_exmatrix(**info: Dict[str, Any]) -> numpy.ndarray
引数が違います

2021-09-06 13:45 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +import numpy as np
参考程度に聞きたいのですが, cyclic permutationで生成できるものと生成できないものの違いって何なんでしょうか?

2021-09-06 13:45 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +def pb_gen_fn(vec:np.ndarray) -> np.ndarray:
細かいですが, `vec: np.ndarray` ですね...(lintがなぜか動いていませんが

2021-09-06 13:45 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +        + [-1 * np.ones(len(vec)).reshape(1, -1)]
```python
length = len(vec)
ex = [np.roll(vec, i) for i in range(length)] + [np.full(length, -1)]
return np.vstack(ex)
```
とかでやればもう少し見やすくなるかも知れません

2021-09-06 14:07 UTC, yo-aka-gene commented on tagupy/design/generator/_pb_ref.py
> +import numpy as np
把握している範囲では、pbのexmatrixが循環行列になっているかいないか？という点と、一番右側の列に1が並んだ縦ベクトルを付け足して、hadamard行列になるかどうか？という点で違っています

2021-09-06 14:12 UTC, yo-aka-gene commented on tagupy/design/generator/__init__.py
> +    "_pb_ref",
_pb_refでほとんど原型を作っておいて、それを削るという実装になっているのと、testのディレクトリ構成が対称的になっていた方が良いかと思ったという２点の理由から、個別にテストを実行できた方が良いかと思い、テストで呼び出したいと考えて呼び出せるようにしてあります

2021-09-06 14:16 UTC, yo-aka-gene commented on tagupy/design/generator/_pb_ref.py
> +def pb_gen_fn(vec:np.ndarray) -> np.ndarray:
そうですね、このファイルごとlint外してあるからですね
直しておきます

2021-09-06 14:35 UTC, yo-aka-gene commented on tagupy/design/generator/_plackettburman.py
> +    get_exmatrix(**info: Dict[str, Any]) -> numpy.ndarray
直しておきます

2021-09-06 14:37 UTC, yo-aka-gene commented on tagupy/design/generator/_pb_ref.py
> +        + [-1 * np.ones(len(vec)).reshape(1, -1)]
ありがとうございます、直しておきます

2021-09-06 14:47 UTC, yo-aka-gene commented on tagupy/design/generator/__init__.py
> +    "_pb_ref",
ユーザー的にはいらないと思うので、隠しファイル的な意味も込めて_を頭文字にしてあります

2021-09-06 15:19 UTC, takesei commented on tagupy/design/generator/__init__.py
> +    "_pb_ref",
`__all__`って以下のやつで読み込まれるものを指定しているだけなのです
```python
from tagupy.design.generator import *
```
なのでそこの欄から消していいと思いますよ

2021-09-06 15:30 UTC, yo-aka-gene commented on tagupy/design/generator/__init__.py
> +    "_pb_ref",
なるほど（勉強不足で申し訳ないです）
削除しておきます

2021-09-06 15:35 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +import numpy as np
understood

2021-09-06 15:39 UTC, takesei approved these changes
THX

2021-09-06 15:39 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +        + [np.full(length, -1)]
二校演算子をbreakするの見にくくないですか...?

2021-09-06 15:39 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +    return pb_gen_fn(vec)
今更感あるかも知れませんが, ほぼ全てのロジックが同じなのであれば, 下に書いてあるもの全て`_pb`で一般化できるかも知れませんね

2021-09-06 15:39 UTC, takesei commented on tagupy/design/generator/_plackettburman.py
> +        ][i // 4] for i in range(100)]
これ毎回毎回`Callable`なオブジェクトが100こも入ったものを作るコードなのでしょうか?

2021-09-06 15:39 UTC, takesei commented
間違えてapproveしました, 実際は変更希望です

2021-09-06 15:46 UTC, gk-hazard commented on tagupy/design/generator/__init__.py
> +    "_pb_ref",
なるほど、僕も行っておきます

2021-09-06 15:46 UTC, gk-hazard commented on tagupy/design/generator/_plackettburman.py
> +            ref._pb84, ref._pb88, ref._pb92, ref._pb96, ref._pb100
少し疑問に思ったのですが、９２が実装できない場合、９６で行うことはできないのですか？

2021-09-06 15:46 UTC, gk-hazard commented on tests/design/generator/test_pb_ref.py
> +            f"shape of retrun var expected (X, X-1) for _pbX, got {matrix.shape} in _pb{num}"
test_pbX_dtype, test_pbX_shapeでは途中まで同じことを行なっていますが、分けた方がそれぞれの機能がわかるから良いということなのでしょうか

2021-09-06 16:00 UTC, yo-aka-gene commented on tagupy/design/generator/_pb_ref.py
> +        + [np.full(length, -1)]
まあ対して長くないのでbreakする必要ないですね、直します

2021-09-06 16:03 UTC, yo-aka-gene commented on tests/design/generator/test_pb_ref.py
> +            f"shape of retrun var expected (X, X-1) for _pbX, got {matrix.shape} in _pb{num}"
まとめます

2021-09-06 16:06 UTC, yo-aka-gene commented on tagupy/design/generator/_plackettburman.py
> +            ref._pb84, ref._pb88, ref._pb92, ref._pb96, ref._pb100
すみません、これに対しての文献を確認できてないので、一応`NotImplementedError`にした次第です
お手数ですが、jmpでn_factorが88から92までと95の実装がどうなってるか、結果をcsvで共有していただけないでしょうか？

2021-09-06 16:08 UTC, yo-aka-gene commented on tagupy/design/generator/_plackettburman.py
> +            ref._pb84, ref._pb88, ref._pb92, ref._pb96, ref._pb100
@gk-hazard

2021-09-06 16:11 UTC, yo-aka-gene commented on tagupy/design/generator/_pb_ref.py
> +    return pb_gen_fn(vec)
一般化します

2021-09-06 16:15 UTC, yo-aka-gene commented on tagupy/design/generator/_plackettburman.py
> +        ][i // 4] for i in range(100)]
変更します

2021-09-06 16:28 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +        + [np.full(length, -1)]
足さないならこういう方法も
```python
[*(np.roll(vec, i) for i in range(len(vec))), np.full(len(vec), -1)]
```

2021-09-06 17:55 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +        + [np.full(length, -1)]
@yo-aka-gene みてね(実装の可否は任せる, 構文的な

2021-09-06 18:04 UTC, yo-aka-gene commented on tagupy/design/generator/_pb_ref.py
> +        + [np.full(length, -1)]
最新版のprが蹴られて、やり直しになったら差し替えておきます

2021-09-07 03:36 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +vec_dict = {
細かいですし今回実装としてはいいですが, Typeについて, この`vec_dict`は`Dict[Union[np.ndarray, Callable[[], np.ndarray]]]`になっています. このunionどちらが適応されるかわからない限り, こういうオブジェクトを使うのはデバッグしにくくなる一つの理由になるかも

2021-09-07 07:41 UTC, yo-aka-gene commented on tagupy/design/generator/_pb_ref.py
> +vec_dict = {
分けてdictにしておきます

2021-09-07 13:24 UTC, takesei requested changes

2021-09-07 13:24 UTC, takesei commented on tagupy/design/generator/_pb_ref.py
> +        else pb_gen_fn(vec_dict[n_run])
基本的に`\`を使ってbreakするのは非推奨です(assertくらい
二行に分けるべきなら, ifを使った方がいいです.

2021-09-07 15:48 UTC, yo-aka-gene commented on tagupy/design/generator/_pb_ref.py
> +        else pb_gen_fn(vec_dict[n_run])
直します

2021-09-08 08:39 UTC, takesei requested changes

2021-09-08 08:39 UTC, takesei commented on tox.ini
> +    tagupy/design/generator/_pb_ref.py,
これ, excludeではなく, `per-file-ignores`を使うべきでは?

2021-09-08 16:49 UTC, yo-aka-gene commented on tox.ini
> +    tagupy/design/generator/_pb_ref.py,
これは確か最初`per-file-ignores`にしてもらったんだけど、竹田と相談してやっぱり`exclude`にしようってなって、こうなったんだけど、なんでこうなったか忘れてしまった

2021-09-08 18:15 UTC, takesei commented on tox.ini
> +    tagupy/design/generator/_pb_ref.py,
理由僕も思い出せないのでここは普通に`per-file-ignores`にしましょう

2021-09-10 01:58 UTC, yo-aka-gene commented on tox.ini
> +    tagupy/design/generator/_pb_ref.py,
了解です

2021-09-10 02:08 UTC, yo-aka-gene commented on tox.ini
> +    tagupy/design/generator/_pb_ref.py,
呼び込ませ行列に関して、見た目の問題と、長さの問題があったので、二つのエラーコードだけ外しておく設定に変えておきました

2021-09-10 02:10 UTC, yo-aka-gene commented on tagupy/design/generator/_plackettburman.py
> +            ref._pb84, ref._pb88, ref._pb92, ref._pb96, ref._pb100
@gk-hazard の調査によって、jmpでも実装できなかったようなので、このままの実装で行きます

2021-09-10 02:10 UTC, yo-aka-gene commented on tagupy/design/generator/_plackettburman.py
> +            ref._pb84, ref._pb88, ref._pb92, ref._pb96, ref._pb100
@gk-hazard の調査によって、jmpでも実装できなかったようなので、このままの実装で行きます

2021-09-10 12:34 UTC, taka-sho requested changes

2021-09-10 12:34 UTC, taka-sho commented on tests/design/generator/test_plackettburman.py
> +    ]
こちら2重のリストになっていますが，期待してるのは単純なリストだと思います

2021-09-10 12:34 UTC, taka-sho commented on tests/design/generator/test_plackettburman.py
> +    ]
上記と同様です

2021-09-10 12:34 UTC, yo-aka-gene commented on tests/design/generator/test_plackettburman.py
> +    ]
直します

2021-09-10 12:34 UTC, yo-aka-gene commented on tests/design/generator/test_plackettburman.py
> +    ]
直します

2021-09-10 13:04 UTC, yo-aka-gene commented on tests/design/generator/test_plackettburman.py
> +    ]
直しました

2021-09-10 13:04 UTC, yo-aka-gene commented on tests/design/generator/test_plackettburman.py
> +    ]
直しました

2021-09-10 13:23 UTC, taka-sho approved these changes

2021-09-10 13:51 UTC, takesei approved these changes
LGTM

2021-09-10 13:51 UTC, merged