Feat/core generator dsd
algebra-club/TaguPy pull request #30
Opened 2021-09-05 12:14 UTC by gk-hazard

* TaguPy version:
* Python version:
* Operating System:

### What
write code for generating DSD

### Why
to achieve requirements of tagupy

2021-09-05 16:33 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd.py
> +    def get_exmatrix(self, n_fac: int, n_fake: int) -> np.ndarray:
n_facとn_fakeが見分けつきにくいと思うのは私だけでしょうか

2021-09-05 16:34 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd.py
> +            number of fake factors which enable better estimation
どのくらいのfake factorにすればいいのか？みたいな説明はしますか？

2021-09-05 16:35 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd.py
> +        ex_mat(: np.ndarray(2(n_fac+n_fake) + 1) * n_fac) if n_fac+n_fake is even)
shapeについての説明の部分が見にくいかもです

もしかしたら改行して、言葉で説明した方がわかりやすいかも

2021-09-05 16:37 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd.py
> +        assert 3 <= sum_fac <= 50,\
sum_facが3以上じゃないといけないっていうのは、説明に書いておかないとユーザーは混乱するかもしれません...

2021-09-05 16:49 UTC, yo-aka-gene commented on tests/design/generator/test_dsd.py
> +    for a, e in zip(correct_input, correct_input):
下のAssertionErrorのeと名前が一致してるのが紛らわしいので、expとかにした方がわかりやすいかなと思いました
（動くなら別に無視でもOKです）

2021-09-05 16:58 UTC, yo-aka-gene commented on tests/design/generator/test_dsd.py
> +    arg1 = ['moge', None, [], 0, -1, 1, 3, 51, 26]
テストコードがイケメンすぎて、難しすぎるかもなので、コメントアウトで補足するか、arg0とarg1の最後を26, 51-26とかに差し替えた方が何してるかわかりやすいかなとおもいました

2021-09-05 16:58 UTC, yo-aka-gene commented on tests/design/generator/test_dsd.py
> +        with pytest.raises(AssertionError) as e:
ここはAssertionErrorがいいですか？NotImplementedErrorではなく？

2021-09-05 17:02 UTC, yo-aka-gene commented on tests/design/generator/test_dsd_ref.py
> +                f'Error: c_mat expected a matrix with zere diagonal, got {diag}'
誤字

2021-09-05 17:07 UTC, yo-aka-gene commented on tests/design/generator/test_dsd_ref.py
> +                    f'{sum_fac}Error: CC′ expected {sum_fac - 2}*I_m,m, got {c_mat @ c_mat.T}'
折角f-stringで{sum_fac - 2}ってやってるのに、I-m,mのmが特に注釈なくつかわれてるのがもったいないかなと思いました

2021-09-05 17:07 UTC, yo-aka-gene commented on tests/design/generator/test_dsd_ref.py
> +                    f'{sum_fac}Error: CC′ expected {sum_fac - 1}*I_m,m, got {c_mat @ c_mat.T}'
上と同じ

2021-09-06 13:54 UTC, takesei requested changes
取り急ぎ

2021-09-06 13:54 UTC, takesei commented on tagupy/design/generator/__init__.py
> +    "_dsd_ref",
これ本当にユーザが読み込む必要がありますか...?

2021-09-06 13:54 UTC, takesei commented on tagupy/design/generator/_dsd.py
> +    def get_exmatrix(self, n_fac: int, n_fake: int) -> np.ndarray:
略さなくてそもそもいいと思います `n_factor`

2021-09-06 13:54 UTC, takesei commented on tagupy/design/generator/_dsd.py
> +            sum_fac += 1
ここ三項演算子でもいいかもね, 参考程度に

2021-09-06 13:54 UTC, takesei commented on tagupy/design/generator/_dsd_ref.py
> +    s = np.concatenate([np.roll(v, i).reshape(1,-1) for i in range(len(v))], axis=0)
参考まで
https://github.com/algebra-club/TaguPy/pull/27#discussion_r702913219

2021-09-06 14:44 UTC, gk-hazard commented on tagupy/design/generator/__init__.py
> +    "_dsd_ref",
自動で読み込めちゃうからってことですか？

2021-09-06 14:50 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd_ref.py
> +    s = np.concatenate([np.roll(v, i).reshape(1,-1) for i in range(len(v))], axis=0)
@takesei ごめん、修正してpushしなおしてresolveしちゃったわ

@gk-hazard コード見てもらうか、resolveしたコメント見てください

2021-09-06 15:17 UTC, gk-hazard commented on tagupy/design/generator/_dsd.py
> +            sum_fac += 1
三項演算子に変えてみました

2021-09-06 15:17 UTC, gk-hazard commented on tests/design/generator/test_dsd.py
> +    for a, e in zip(correct_input, correct_input):
変更しました

2021-09-06 15:17 UTC, gk-hazard commented on tests/design/generator/test_dsd.py
> +    arg1 = ['moge', None, [], 0, -1, 1, 3, 51, 26]
わかりにくかったですね、コメントアウトしておきました

2021-09-06 15:17 UTC, gk-hazard commented on tests/design/generator/test_dsd.py
> +        with pytest.raises(AssertionError) as e:
dsd.py ではassertion errorにしています。notimplemented errorに変更した方がいいですか？

2021-09-06 15:21 UTC, takesei commented on tagupy/design/generator/__init__.py
> +    "_dsd_ref",
```python
from tagupy.design.generator import *
```
で, `_dsd_ref`は読み込める必要がありますか? という意味です

2021-09-06 15:44 UTC, yo-aka-gene commented on tests/design/generator/test_dsd.py
> +        with pytest.raises(AssertionError) as e:
正直、好みの問題かなとも思います
あとで50以上も実装するつもりがあるなら`NotImplementedError`の方があとで実装するつもりがあるということが伝わると思います！
原理上無理とか、実装するつもりがないなら`AssertionError`でもいいと思うので、resolveしてください！

2021-09-06 15:50 UTC, yo-aka-gene commented on tagupy/design/generator/__init__.py
> +from . import _dsd_ref
import したのに使ってないです
（make lintで指摘されるはずなので、お忘れなく！）

2021-09-06 15:56 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd_ref.py
> +    zero_vec = np.array([0 for i in range(len(c_mat))]).reshape(1, -1)
完全に揚げ足取りではありますが、`axis=0`でconcatenateしたいのに、`len(c_mat)`は少し分かりにくいかと思います。
```
zero_vec = np.zeros(c_mat.shape[1])
d_mat = np.vstack([c_mat, -c_mat, zero_vec])
```
はいかがでしょうか？

2021-09-06 15:57 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd_ref.py
> +    d_mat = np.concatenate([c_mat, -c_mat, zero_vec], axis=0)[:, :n_factor]
完全に揚げ足取りではありますが、`axis=0`でconcatenateしたいのに、`len(c_mat)`は少し分かりにくいかと思います。
```
zero_vec = np.zeros(c_mat.shape[1])
d_mat = np.vstack([c_mat, -c_mat, zero_vec])[:, :n_factor]
```
はいかがでしょうか？

2021-09-06 15:59 UTC, gk-hazard commented on tests/design/generator/test_dsd.py
> +        with pytest.raises(AssertionError) as e:
なるほど、了解しました。多分今後実装するつもりないので、とりあえず今はこのままにしておきます

2021-09-06 16:00 UTC, gk-hazard commented on tagupy/design/generator/__init__.py
> +    "_dsd_ref",
ゆうじのpr見て理解しました。
変更を加えておきました

2021-09-06 16:04 UTC, gk-hazard commented on tagupy/design/generator/_dsd_ref.py
> +    d_mat = np.concatenate([c_mat, -c_mat, zero_vec], axis=0)[:, :n_factor]
ありがとう、綺麗になりました。型と形のみ少し変更しましたが、ほとんどパクらせてもらいました

2021-09-10 13:57 UTC, yo-aka-gene commented on tox.ini
> +    tagupy/design/generator/_dsd_ref.py,
`per-file-ignores`の方が良いとのことです

2021-09-10 14:00 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd_ref.py
> +def _dsdeq3(sum_fac: int, gen_vec: dict[int, List[int]]) ->np.ndarray:
`dict`が大文字になってないです！
`from typing import List, Dict`でインポートできます！

2021-09-10 14:01 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd_ref.py
> +def _cmateq2(sum_fac: int, gen_vec: dict[int, List[List[int]]]) ->np.ndarray:
ここもね

2021-09-10 14:02 UTC, yo-aka-gene commented on tagupy/design/generator/_dsd_ref.py
> +def _dsddb(sum_fac: int, gen_vec: dict[int, List[int]]) ->np.ndarray:
ここもね

2021-09-11 02:27 UTC, takesei approved these changes
LGTM

2021-09-11 02:57 UTC, yo-aka-gene approved these changes
LGTM
[](https://livedoor.blogimg.jp/creator_mag_ja/imgs/4/8/4864ab70.jpg)

2021-09-11 10:54 UTC, merged