feat(workflows/lint) lint checking
algebra-club/TaguPy pull request #7
Opened 2021-08-17 19:24 UTC by taka-sho

* TaguPy version: *
* Python version: 3.7
* Operating System: *

### What

Check lint, test, and coverage on CI.

### Why

This project needs the quality-checks.

2021-08-20 23:15 UTC, takesei requested changes
朝早くからPRありがとうござます.
確認しましたので対応よろしくお願いします

2021-08-20 23:15 UTC, takesei commented on .github/workflows/quality_checks.yml
> +        run: make coverage
coverageの情報は, `codecov` を通じて視覚化することができます. 
このままでは上記同様結果が出力されない上, coverageの網羅率(これもcoverageなので混同しますね)が低かった時にrejectすると言うものもついてないように思えます
参考まで
https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/

2021-08-20 23:15 UTC, takesei commented on .github/workflows/quality_checks.yml
> +    runs-on: ubuntu-latest
https://docs.github.com/ja/actions/guides/building-and-testing-python

strategyを用いて複数pythonバージョンを対象にテストを組むこともできますよ, 参考まで

2021-08-20 23:15 UTC, takesei commented on .github/workflows/quality_checks.yml
> +on: [pull_request]
pushされるタイミングでも発動するといいかもしれません.
あと, targetはmasterだけにしなくても大丈夫?

2021-08-20 23:15 UTC, takesei commented on .github/workflows/quality_checks.yml
> +        run: make lint
基本的にlintした結果など, errorが出てわからなくなった場合, githubactionsでは可視化されない(Log見ないと辛い)ので, 一般にreviewdogなどが使用されます.

https://github.com/marketplace/actions/python-flake8-lint

こう言うものもあるので入れてみてはどうでしょうか, ご参考まで

2021-08-20 23:15 UTC, takesei commented on .github/workflows/quality_checks.yml
> +        run: make test
よく考えると, `make test-all` では一緒にlintしてしまいますね.
`poetry run tox` とかでもいいかもしれません

2021-08-20 23:20 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +        run: make lint
pythonはwarning等がPR上では出ないんですね。

2021-08-20 23:21 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +        run: make test
手元でtest-allが通らず、とりあえず実装したのを忘れてました

2021-08-20 23:22 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +        run: make coverage
またcodecovを使う流れになってるんですね（一時期死んでいた時期があったので）

2021-08-20 23:24 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +    runs-on: ubuntu-latest
toxとstrategyの併用はどのように実装するのがベターなんですかね

2021-08-20 23:24 UTC, takesei commented on .github/workflows/quality_checks.yml
> +        run: make lint
coverageはoptionでもしかしたらthresholdを設定できたかもしれません.
ただlintは警告が出てきたとしても, 落ちるだけでどこで死んだかはLog見ないといけないことに変わりはないですね.
いずれにしても結果は常に投稿させたほうがいいことが多いです

2021-08-20 23:25 UTC, takesei commented on .github/workflows/quality_checks.yml
> +        run: make test
通らなかった理由はおそらく環境の再現ができてないからですね
今日現地でも対応します

2021-08-20 23:27 UTC, takesei commented on .github/workflows/quality_checks.yml
> +        run: make coverage
今も死んでるけどあまり他に方法もないですね, artifactにhtml投げちゃうって言うのはありですが

c.f. https://about.mercari.com/press/news/articles/20210521_incident_report/

2021-08-20 23:29 UTC, takesei commented on .github/workflows/quality_checks.yml
> +    runs-on: ubuntu-latest
toxが複数バージョンでのテストを要求している...というだけなので, strategyで複数指定してあげて, それをtoxで動かしてあげるっていう流れです

2021-08-20 23:30 UTC, takesei commented on .github/workflows/quality_checks.yml
> +    runs-on: ubuntu-latest
https://github.com/ymyzk/tox-gh-actions

READMEのWorkflow Configurationにもその趣旨乗ってます

2021-08-21 07:36 UTC, k-kyoko commented
nanachi

2021-08-21 07:41 UTC, k-kyoko commented
banananaci

2021-08-21 08:35 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +    runs-on: ubuntu-latest
:done:

2021-08-21 08:35 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +        run: make lint
reviewdog を導入しました

2021-08-21 08:35 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +        run: make coverage
codecov を導入しました．

2021-08-21 08:57 UTC, takesei requested changes

2021-08-21 08:57 UTC, takesei commented on .github/workflows/quality_checks.yml
> +          python-version: 3.9
`env`にしたほうがいいのでは？

2021-08-21 08:57 UTC, takesei commented on .github/workflows/quality_checks.yml
> +        python-version: [3.7, 3.8, 3.9]
`env` again

2021-08-21 08:57 UTC, takesei commented on .github/workflows/quality_checks.yml
> +          python-version: 3.9
`env`

2021-08-21 08:57 UTC, takesei commented on .python-version
> +3.9.0
環境の問題があるのでからでもいいかも?

2021-08-21 09:09 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +          python-version: 3.9
envに設定しました

2021-08-21 09:09 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +        python-version: [3.7, 3.8, 3.9]
DONE

2021-08-21 09:09 UTC, taka-sho commented on .github/workflows/quality_checks.yml
> +          python-version: 3.9
DONE

2021-08-21 09:10 UTC, taka-sho commented on .python-version
> +3.9.0
空にしました

2021-08-21 09:12 UTC, takesei approved these changes
お疲れ様でした

2021-08-21 09:13 UTC, merged